### ISSUE TITLE
如何解决超过9个eth后，单位转换未wet后，超过php_int_max的问题

### ISSUE THREAD

**Issue by yangmeishu** [myxtype/ethereum-client#1]

**Comment by myxtype** [comment]
使用Utils类的静态函数进行转换，使用PHP的bc函数进行计算。

**Comment by yangmeishu** [comment]
老哥你回复很快。。。
我的场景是这样，用户充值后，我需要马上把用户的币转到我的账户，这样的情况需要尽可能的把用户所有的余额清空，也就意味着我需要把eth转换成wet，然后减去燃料费。
感谢，因为有看你的转账例在使用了自带的hexdec函数，没留意utils的方法，现在用bc函数处理减法和使用utils的10进制转换成16进制。
