### ISSUE TITLE
老哥离线生成的地址有撞车的存在！

### ISSUE THREAD

**Issue by wwx101123** [myxtype/ethereum-client#4]
在生产环境中，发现用户并未充值，而且上账了，倒并未造成损失，只不过同一时间别人也使用此库，生成的地址和私钥撞车了，这个如何解决？可以在加密算法中自定义一个秘钥来防止此类问题么？

**Comment by myxtype** [comment]
我根据github弹出的安全提示更新了漏洞库，不知道能不能修复此Bug，因为好久没用此库了，我们早在一年前已经转向Golang语言了。
